/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const assert: typeof import('chai')['assert']
  const describe: typeof import('mocha')['describe']
  const error: typeof import('./packages/app/api')['error']
  const info: typeof import('./packages/app/api')['info']
  const it: typeof import('mocha')['it']
  const log: typeof import('./packages/app/api')['log']
  const warn: typeof import('./packages/app/api')['warn']
}
