/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const assert: typeof import('chai')['assert']
  const describe: typeof import('mocha')['describe']
  const info: typeof import('consola')['info']
  const it: typeof import('mocha')['it']
  const log: typeof import('consola')['log']
  const warn: typeof import('consola')['warn']
}
